import { Header } from "./(site)/components/Header";
import { Footer } from "./(site)/components/Footer";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@/styles/theme.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} bg-bg-main text-text-main`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
